apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstrap
  namespace: argocd
spec:
  destination:
    name: in-cluster
  project: default
  source:
    path: apps
    repoURL: https://github.com/plasticaxe/intro-argo-cd-tutorial # Update to your repo URL.
    targetRevision: HEAD
